Agenda/ExemplosWeb/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from ExemplosWeb.views import homepage, homeSec , registro,MeuUpdateView
from django.contrib.auth.views import LoginView , LogoutView
from django.urls.base import reverse_lazy
from django.contrib.auth.views import PasswordChangeView,PasswordChangeDoneView
from django.views.generic.edit import UpdateView
from django.contrib.auth.models import User





urlpatterns = [
    path('admin/', admin.site.urls),
    path("Filmes/", include ('Filmes.urls')),
    path('',homepage,name = 'tela-inicial'),
    path('accounts/',homeSec,name='sec-home'),
    path('accounts/registro/',registro, name = 'sec-registro'),
    path('accounts/login/',LoginView.as_view(template_name='registro/login.html'),name = 'sec-login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('sec-login'),), name='sec-logout'),
    path('accounts/password_change/',PasswordChangeView.as_view(template_name='registro/password_change_form.html',success_url=reverse_lazy('sec-password_change_done'),), name = 'sec-troca-senha'),
    path('accounts/senhaTrocada/',PasswordChangeDoneView.as_view(template_name='registro/password_change_done'), name = 'sec-senha-trocada'),
    path('accounts/terminaRegistro/<int:pk>/',MeuUpdateView.as_view(template_name='registro/user_form.html',success_url=reverse_lazy('sec-home'),model=User,fields=['first_name','last_name','email',],), name='sec-termina-registro'),

]

Agenda/Filmes/urls.py
from django.urls.conf import path
from Filmes import views
from django.contrib.auth import views as auth_views
app_name = "Filmes"
urlpatterns = [
path('cria/', views.FilmeReviewCreate.as_view(),name='cria-review'),
path('lista/', views.FilmeList.as_view(),name='lista-review'),
path('atualiza/<int:pk>/',views.FilmeReviewUpdate.as_view(),name='atualiza-review'),
path('apaga/<int:pk>/',views.FilmeReviewDelete.as_view(),name='apaga-review'),
path('', views.FilmeList.as_view(),name='home-review'),
]

Agenda/contatos/urls.py
from django.urls.conf import path
from contatos import views
app_name = "contatos"
urlpatterns = [
path('cria/', views.ContatoCreateView.as_view(),name='cria-contato'),
path('lista/', views.ContatoListView.as_view(),name='lista-contatos'),
path('atualiza/<int:pk>/',views.ContatoUpdateView.as_view(),name='atualiza-contato'),
path('apaga/<int:pk>/',views.ContatoDeleteView.as_view(),name='apaga-contato'),
path('', views.ContatoListView.as_view(),name='home-contatos'),
]

Agenda/Filmes/models.py
from django.db import models

# Create your models here.

class FilmeReview (models.Model):
    filme = models.CharField(max_length=100, help_text='Entre o nome do filme')
    review = models.CharField(max_length=500, help_text='Escreva sua review')
    nota = models.IntegerField(help_text='Qual nota você da?')

Agenda/Filmes/forms.py
from django import forms
from Filmes.models import FilmeReview


class FilmeReviewModel(forms.ModelForm):
    class Meta:
        model = FilmeReview
        fields = '__all__'

Agenda/ExemplosWeb/views.py
from django.shortcuts import render , redirect
from datetime import datetime
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView


def homepage(request):
    agora = datetime.now()
    relogio = {
    "dia" :agora.day,
    "mes" :agora.month ,
    "ano" :agora.year ,
    "hora" :agora.hour ,
    "minuto" :agora.minute ,
    }   

    return render(request,'ExemplosWeb/index.html',relogio)

def homeSec(request):
    return render(request,"registro/homeSec.html")


    
def registro(request):
    if request.method =='POST':
        formulario = UserCreationForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect('/')
        else:
            return render(request,'registro/registro.html', {'form': formulario, })
    else:
        formulario = UserCreationForm()
        return render(request,'registro/registro.html', {'form': formulario, })



class MeuUpdateView(UpdateView):
    def get(self,request,pk,*args,**kwargs):
        if request.user.id == pk:
            return super().get(request,pk,args,kwargs)
        else:
            return redirect('sec-home')

    def post(self,request,pk,*args,**kwargs):
        if request.user.id == pk:
            return super().post(request,pk,args,kwargs)
        else:
            return redirect('sec-home')
            

Agenda/Filmes/views.py
# Create your views here.

from django.shortcuts import render, get_object_or_404
from Filmes.models import FilmeReview
from django.views.generic.base import View
from Filmes.forms import FilmeReviewModel
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

class FilmeList(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        reviews = FilmeReview.objects.all()
        context = { 'reviews': reviews, }
        return render(request,'Filmes/listaReview.html',context)

class FilmeReviewCreate(View):
    def get(self, request, *args, **kwargs):
        #retorna apenas 1 objeto, senão levanta uma excessão
        context = {'formulario': FilmeReviewModel}
        return render(request, 'Filmes/criaReview.html', context)

    def post(self, request, *args, **kwargs):
        formulario = FilmeReviewModel(request.POST)
        if formulario.is_valid():
            review = formulario.save()      #cria um objeto pessoa para o BD
            review.save()                  #cria um registro pessoa no BD
            return HttpResponseRedirect(reverse_lazy('Filmes:home-review'))
        else:
            return render(request, 'Filmes/criaReview.html', {'formulario':formulario})

class FilmeReviewUpdate(View):
    def get(self, request, pk, *args, **kwargs):
        #retorna apenas 1 objeto, senão levanta uma excessão
        review = FilmeReview.objects.get(pk=pk)
        formulario = FilmeReviewModel(instance=review)
        context = {'review': formulario, }
        return render(request, 'Filmes/atualizaReview.html', context)

    def post(self, request, pk, *args, **kwargs):
        review = get_object_or_404(FilmeReview, pk=pk)
        formulario = FilmeReviewModel(request.POST, instance=review)
        if formulario.is_valid():
            review= formulario.save()	# cria uma pessoa com os dados do formulário
            review.save()									# salva uma pessoa no banco de dados
            return HttpResponseRedirect(reverse_lazy("Filmes:home-review"))
        else:
            contexto = {'review': formulario, }
            return render(request, 'Filmes/atualizaReview.html', contexto)
            

class FilmeReviewDelete(View):
    def get(self, request, pk, *args, **kwargs):
        review = FilmeReview.objects.get(pk=pk)
        contexto = { 'review': review, }
        return render(
            request, 'Filmes/apagaReview.html', 
              contexto)

    def post(self, request, pk, *args, **kwargs):
        review = FilmeReview.objects.get(pk=pk)
        review.delete()
        return HttpResponseRedirect(
            reverse_lazy("Filmes:home-review"))

Agenda/ExemplosWeb/templates/ExemplosWeb/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Pagina Inicial</h1>

    <p>
        Bem vindo usuário
    </p>
    <p>
        {{ dia }}/{{mes}}/{{ano}}
        <br> <br/>
        {{hora}}:{{minuto}}
    </p>
    {%if user.is_authenticated %}
    <p>

        <ul>
            <li><a href="{% url 'Filmes:home-review' %}" style = "text-decoration: none;" >Clique aqui  </a> para ir para suas resenhas </li>

        </ul>
    </p>
    {% else %}
        <a href="{% url 'sec-login' %}">Clique aqui para fazer Login</a>
    {% endif %}

</body>


</html>

Agenda/ExemplosWeb/templates/registro/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block titulo %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'Filme/css/estilo.css' %}">
    
</head>
<body>    
    <div>
        {%if user.is_authenticated %}
            |<a href='{%url "sec-logout" %}'>Logout</a>
            |<a href="{% url 'sec-troca-senha' %}">Trocar senha</a>
            |<a href="{% url 'sec-termina-registro' pk=user.id %}">documento</a>
            <a href="{% url 'Filmes:home-review' %}">Reviews</a>

        {% else %}
        {% endif %}





    | Você está logado como {% firstof user.username "visitante" %}
    </div>
    <hr>
    {% block conteudo %}{% endblock %}
</body>
</html>

Agenda/ExemplosWeb/templates/registro/homeSec.html
{% extends 'registro/base.html' %}

{% block titulo %} 
Pagina Inicial
{% endblock %}
{% block conteudo %} 
<h2> Pagina inicial de cadastro de usuários </h2>
{% endblock %}

Agenda/ExemplosWeb/templates/registro/login.html
{% extends 'registro/base.html' %}

{% block titulo %} 
Pagina de Login
{% endblock %}
{% block conteudo %} 
<h2> Pagina inicial de Login de usuários </h2>
<form action = "" method="post">
    {% csrf_token %}
    <table class="formulario">
        {{ form.as_table }}
    <tr>
        <td colspan="2">
            <input type="submit" value="Login">
            <a href="{% url 'sec-registro' %}">Registrar-se</a>
        </td>
    </tr>
    </table>
</form>
{% endblock %}

Agenda/ExemplosWeb/templates/registro/password_change_done.html
{% extends 'registro/base.html' %}

{% block titulo %} 
<h2>  Pagina para o usuário trocar sua senha </h2>
{% endblock %}

{% block conteudo %}
<p>Senha trocada com sucesso</p>

{% endblock %}

Agenda/ExemplosWeb/templates/registro/password_change_form.html
{% extends 'registro/base.html' %}

{% block titulo %} 
Pagina de Troca de senha
{% endblock %}
{% block conteudo %} 
<h2> Pagina inicial de troca de senha do usuários </h2>
<form action = "" method="post" class="formulario">
    {% csrf_token %}
    <table class="formulario">
        {{ form.as_table }}
    <tr>
        <td colspan="2">
            <input type="submit" value="Troca senha">

        </td>
    </tr>
    </table>
</form>
{% endblock %}

Agenda/ExemplosWeb/templates/registro/recupera/password_reset_email.html
<!DOCTYPE html>

<html>

<head>
    <meta charset="UTF-8">
    <title>Recuperação de Senha de {{domain}}</title>
</head>

<body>
    <p>Alguém solicitou em {{ protocol }}://{{ domain }} email para {{ email }}
de redefinição da senha da sua conta {{ user }}</p>
<p>Por favor, acesse a seguinte página e escolha uma nova senha:</p>
{% url 'password_reset_confirm' uidb64=uid token=token as link %}
<p>
<a href=
"{{ protocol}}://{{ domain }}{{ link }}">{{ protocol}}://{{ domain }}{{ link }}</a>
</p>
<p>Seu nome de usuário, caso tenha esquecido: <b>{{ user }}</b></p>
<p>Obrigado por usar nosso site!</p>
<p>Equipe {{ domain }}</p>
</body>
</html>

Agenda/ExemplosWeb/templates/registro/registro.html
{% extends 'registro/base.html' %}

{% block titulo %} 
Pagina de registro
{% endblock %}
{% block conteudo %} 
<h2> Pagina inicial de registro de usuários </h2>
<form action = "" method="post">
    {% csrf_token %}
    <table class="formulario">
        {{ form.as_table }}
    <tr>
        <td colspan="2">
            <input type="submit" value="Registrar">

        </td>
    </tr>
    </table>
</form>
{% endblock %}

Agenda/ExemplosWeb/templates/registro/user_form.html
{% extends 'registro/base.html' %}

{% block titulo %} 
Pagina para completar o registro
{% endblock %}
{% block conteudo %} 
<h2> Pagina inicial de completar registro </h2>
<form action = "" method="post" class="formulario">
    {% csrf_token %}
    <table class="formulario">
        {{ form.as_table }}
    <tr>
        <td colspan="2">
            <input type="submit" value="Atualiza dados">

        </td>
    </tr>
    </table>
</form>
{% endblock %}

Agenda/Filmes/templates/Filmes/apagaReview.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Apaga review</title>
    <link rel="stylesheet" href="{% static 'Filmes/css/estilo.css' %}">
    
</head>
<body>
    {% include 'Filmes/linksHeader.html' %}
  <h1>Remoção de reviews</h1>
  <form method="POST">
    {% csrf_token %}
   Confirma a remoção de {{ review }}?<br>
   <button>
       <a href="{% url 'Filmes:lista-review' %}" 
          style="text-decoration: none; color: black;">Cancela</a>
   </button>
   <input type="submit" value="Remove">
</form>
</body>
</html>

Agenda/Filmes/templates/Filmes/atualizaReview.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Atualiza review</title>
    <link rel="stylesheet" href="{% static 'contatos/css/form.css' %}">
    
</head>
<body>
    {% include 'Filmes/linksHeader.html' %}
  <h1>Atualização de review</h1>
  <form method="POST" class='formulario'>
    {% csrf_token %}
    <table>
      {{ review.as_table }}
    </table>
  </form>
  <input type="submit" value="Atualiza" class="button">
</body>
</html>

Agenda/Filmes/templates/Filmes/criaReview.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'contatos/css/form.css' %}">
</head>
<div>
<body>
    {% include 'Filmes/linksHeader.html' %}
    <h1>Criar um review</h1>
        <form action="" method="post" class="formulario">
            {% csrf_token %}
            <table class="formulario">
                {{ formulario.as_table }}
            </table>
        </form>
        <input type="submit" value="Criar review" class="button">
</body>
</div>
</html>

Agenda/Filmes/templates/Filmes/linksHeader.html
<!--
Para incluir esse fragmento de página HTML
em uma página HTML use:
{ % include 'contatos/links.html' % }
-->
<a href="/">
    Página principal
</a> |
<a href="{% url 'Filmes:lista-review' %}">
    Lista de reviews
</a> |
<a href="{% url 'Filmes:cria-review' %}">
    Cria review
</a> |
<a href='{%url "sec-logout" %}'>Logout</a>

<hr>

Agenda/Filmes/templates/Filmes/listaReview.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Lista de resenhas</title>
    <link rel="stylesheet" href="{% static 'contatos/css/listaReview.css' %}">
</head>

<body>
    {% include 'Filmes/linksHeader.html' %}
    <div class="content">
        <h1>Lista de resenhas</h1>
        <table class="styled-table">
            <thead> 
                <tr class="table-header">
                    <th>Filme</th>
                    <th>Review</th>
                    <th>Nota</th>
                    <th>Opções</th>
                </tr>
            </thead>
            <tbody> 
                {% for review in reviews %}
                <tr>
                    <td>{{review.filme }}</td>
                    <td>{{ review.review }}</td>
                    <td>{{ review.nota }}</td>
                    <td>
                <a href="{% url 'Filmes:atualiza-review' pk=review.id %}">Atualizar</a> |
                <a href="{% url 'Filmes:apaga-review' pk=review.id %}">Excluir</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5">Ainda não tem resenhas cadastradas</td>
        </tr>
        {% endfor %}
    </tbody> 
</table>
</div>
</body>

</html>

Agenda/contatos/templates/contatos/apagaContato.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Apaga Contato</title>
    <link rel="stylesheet" href="{% static 'contatos/css/estilo.css' %}">
    
</head>
<body>
    {% include 'contatos/links.html' %}
  <h1>Remoção de contatos</h1>
  <form method="POST">
    {% csrf_token %}
   Confirma a remoção de {{ pessoa }}?<br>
   <button>
       <a href="{% url 'contatos:lista-contatos' %}" 
          style="text-decoration: none; color: black;">Cancela</a>
   </button>
   <input type="submit" value="Remove">
</form>
</body>
</html>

Agenda/contatos/templates/contatos/atualizaContato.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Atualiza Contatos</title>
    <link rel="stylesheet" href="{% static 'contatos/css/estilo.css' %}">
    
</head>
<body>
    {% include 'contatos/links.html' %}
  <h1>Atualização de contatos</h1>
  <form method="POST" class='formulario'>
    {% csrf_token %}
    <table>
      {{ pessoa.as_table }}
        <tr>
          <td></td>
          <td><input type="submit" value="Atualiza"></td>
        </tr>
    </table>
  </form>
</body>
</html>

Agenda/contatos/templates/contatos/criaContato.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'contatos/css/estilo.css' %}">
</head>
<body>
    {% include 'contatos/links.html' %}
        <form action="" method="post" class="formulario">
            {% csrf_token %}
            <table>
                {{ formulario.as_table }}
            </table>
            <input type="submit" value="Cria1Contato">
        </form>
</body>
</html>

Agenda/contatos/templates/contatos/links.html
<!--
Para incluir esse fragmento de página HTML
em uma página HTML use:
{ % include 'contatos/links.html' % }
-->
<a href="/">
    Home-Page
</a> |
<a href="{% url 'contatos:home-contatos' %}">
    Página inicial
</a> |
<a href="{% url 'contatos:lista-contatos' %}">
    Listar contatos
</a> |
<a href="{% url 'contatos:cria-contato' %}">
    Cria Contato
</a> |

<hr>